name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

env:
  REGISTRY: quay.io

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [archive2disk,cexec,grub2disk,image2disk,kexec,oci2disk,qemuimg2disk,rootio,slurp,syslinux,writefile]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Prepare Release
        run: make prepare-release

      - name: Run Release
        run: make release-${{ matrix.action }} -j $(nprox)
