name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        run: docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

      - name: Prepare Release
        run: make prepare-release

      - name: Run Release
        run: make release -j $(nprox)

      - name: Clean up Release
        run: make clean-release
