name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

env:
  REGISTRY: quay.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Prepare Release
        run: make prepare-release

      - name: Run Release
        run: make release -j $(nprox)

      - name: Clean up Release
        run: make clean-release
